Repository OZ-Coding-School/oz_02_collabo-004, pull requests merged in 2024-05, with the labels that each got.

#122 Style: MypaymentList 페이지 gap, padding, Location 위치 수정
  src/pages/MyPage/MyPaymentListPage.jsx
Labels: style

#135 Refactor: PaymentComplete 코드 정리
  src/App.jsx
  src/pages/index.js
Labels: refactor

#143 [Feat] IndexPage, ChallengePage 슬라이드 기능 구현
  src/components/BookCaroussel/BookCarrousel.jsx
  src/pages/Challenge/ChallengePage.jsx
  src/pages/Home/IndexPage.jsx
Labels: feature

#155 Feat: admin 책 등록 수정 UI
  src/components/AdminRecommendSpolier/index.jsx
  src/pages/Admin/AdminBookCreatePage.jsx
  src/pages/BookSpoiler/BookSpoilerPage.jsx
  src/pages/MyPage/MyPaymentListPage.jsx
  src/pages/Payment/PaymentPage.jsx
Labels: feature, style

#164 [Feat] Header 간격변경
  src/components/@common/Header/Header.jsx
Labels: feature

#167 Refactor: admin 도서 등록/수정 관련 코드수정
  src/components/AdminRecommendSpoiler/index.jsx
  src/pages/Admin/AdminBookCreatePage.jsx
Labels: refactor

#170 163 feat 회원정보 기본이미지 변경 input에 placeholder 변경
  src/assets/images/profileImage-1.jpg
  src/assets/images/profileImage-2.jpg
  src/components/@common/Input/index.jsx
  src/pages/MyPage/MyInfoPage.jsx
Labels: feature

#171 Refactor: statusCard 변경될 때 scrollTop
  src/components/BookComment/index.jsx
Labels: refactor

#172 [Feat] Admin 댓글관리 페이지
  src/pages/Admin/AdminCommentPage.jsx
Labels: feature

#173 Refactor: ChallengeActionPage > 챌린지 완료 댓글 후 qurator spoiler 변화 수정
  src/pages/Challenge/ChallengeActionPage.jsx
Labels: refactor

#174 Style: BookCard 스타일 변경
  src/components/BookInfoCard/index.jsx
Labels: style

#176 Feat: BookCard 외부 링크 3개 초과 클릭시 모달창 구현
  package-lock.json
  package.json
  src/components/BookInfoCard/BookCardLinkNone.jsx
  src/components/BookInfoCard/Modal.jsx
  src/components/BookInfoCard/index.jsx
Labels: feature

#177 Feat: 카카오톡, BookSpoilerDetail > api 폴더 및 기능, 랜덤 컬러 util 파일
  src/api/book/index.js
  src/api/comment/index.js
  src/api/common/index.js
  src/api/keyword/index.js
  src/components/BookComment/index.jsx
  src/pages/BookSpoiler/BookSpoilerDetailPage.jsx
  src/pages/Login/LoginPage.jsx
  src/utils/RandomColor.js
Labels: feature

#180 [Refactor] Header 컴포넌트
  src/components/@common/Header/Header.jsx
Labels: refactor

#183 remove .env file from git repo
  .env
Labels: bug

#186 [Feat] HomePage 메인배너, 상세이미지 변경
  src/assets/images/bookspoilerDetail.png
  src/assets/images/bookspoilerMain.png
  src/pages/Home/IndexPage.jsx
Labels: refactor

#187 Feat: useMutate 수정
  src/api/book/index.js
  src/api/comment/index.js
  src/api/common/index.js
  src/api/keyword/index.js
  src/components/@common/Modal/index.jsx
  src/components/BookComment/BookDeleteComment.jsx
  src/components/BookComment/BookEditComment.jsx
  src/components/BookComment/index.jsx
  src/hooks/useFetch.js
  src/hooks/useMutate.js
  src/pages/BookSpoiler/BookSpoilerDetailPage.jsx
Labels: feature

#199 [Feat] 챌린지 페이지 상세설명 이미지 변경
  src/assets/images/challengeDetail.gif
  src/pages/Challenge/ChallengePage.jsx
Labels: feature

#200 197 feat challengeactionpage 현황 user doing 프로퍼티로 기능 수정
  src/App.jsx
  src/components/@common/Header/AdminHeader.jsx
  src/components/@common/Header/Header.jsx
  src/components/ChallengeStatus/index.jsx
  src/components/MyPageSidebar/index.jsx
  src/pages/Challenge/ChallengeActionPage.jsx
  src/pages/Login/LoginPage.jsx
Labels: feature

#202 Refactor: 경로수정, 헤더 마이페이지 메뉴 추가 (로그인 한 경우)
  src/App.jsx
  src/components/@common/Header/Header.jsx
  src/pages/Challenge/ChallengeActionPage.jsx
Labels: refactor

#208 Feat: 목업 데이터 추가 / api 연동 테스트
  package-lock.json
  package.json
  src/assets/images/bookimg/book1.jpeg
  src/assets/images/bookimg/book10.jpeg
  src/assets/images/bookimg/book2.jpeg
  src/assets/images/bookimg/book3.jpeg
  src/assets/images/bookimg/book4.jpeg
  src/assets/images/bookimg/book5.jpeg
  src/assets/images/bookimg/book6.jpeg
  src/assets/images/bookimg/book7.jpeg
  src/assets/images/bookimg/book8.jpg
  src/assets/images/bookimg/book9.jpeg
  src/components/BookInfoCard/BookCardKeyword.jsx
  src/components/BookInfoCard/KeywordData.js
  src/components/BookInfoCard/data.js
  src/components/BookInfoCard/index.jsx
  src/components/PaymentList/index.jsx
  src/pages/BookSpoiler/BookSpoilerPage.jsx
  src/pages/MyPage/MyPaymentListPage.jsx
Labels: feature

#210 Refactor: 북스포일러 상세페이지로 통하는 링크 주소 수정
  src/components/BookInfoCard/index.jsx
Labels: refactor

#214 [Feat] 회원정보 페이지 api연동 주석처리
  src/components/@common/Input/index.jsx
  src/pages/MyPage/MyInfoPage.jsx
Labels: feature
